name: poi package
defaults:
  run:
    shell: bash
    working-directory: apis/poi
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'apis/poi/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet build .
    - name: Test
      run: dotnet test . 