on:
  push:
    branches:
      - main
    paths:
      - 'apis/user-java/**'

  workflow_dispatch:

name: user-java-cd

env:
  REPO_NAME: devopsoh/api-user-java    # per api
  RESOURCE_GROUP: openhack8ep4f6r5rg
  APP_NAME: openhack8ep4f6r5userjava

defaults:
  run:
    shell: bash
    working-directory: apis/user-java    # per api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Deployment Validation'
        working-directory: resources
        run: ./polling.sh https://${{ env.APP_NAME }}-staging.azurewebsites.net/api/healthcheck/user-java
      
      #- name: 'Swap Azure Containers'
      #  run: az webapp deployment slot swap -g ${{ env.RESOURCE_GROUP }} -n ${{ env.APP_NAME }} --slot staging --target-slot production
