# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: user-java Maven Package

env:
  MAVEN_HOME: apis/user-java

on:

  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - 'apis/user-java/**'
      # - ${{ env.MAVEN_HOME }}/**


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      issues: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      working-directory: ${{ env.MAVEN_HOME }}
      run: mvn clean install

    - name: Test Maven
      working-directory: ${{ env.MAVEN_HOME }}
      run: mvn test
      
    - name: Create issue using REST API
      if: ${{ failure() }}
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Automated issue for commit: ${{ github.sha }}",
          "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
          }' \
        --fail