on:
  push:
    paths:
      - 'apis/user-java/**'

  workflow_dispatch:

name: user-java-cd

env:
  REPO_NAME: devopsoh/api-user-java    # per api
  APP_NAME: openhack8ep4f6r5userjava

defaults:
  run:
    shell: bash
    working-directory: apis/user-java    # per api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$REPO_NAME:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$REPO_NAME:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: azure/webapps-deploy@v2
        with:
          #app-name: openhack8ep4f6r5userjava
          app-name: ${{ env.APP_NAME }}
          #images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-user-java:${{ github.sha }}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.REPO_NAME }}:${{ github.sha }}
